# Generated by Django 5.0.2 on 2024-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('name', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
